---
title: "ALL tests - condition comparisons"
author: "Benjamin Holding"
date: "18/12/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
priors_score = c(set_prior("normal(2.25,2.25)", class = "b", lb = -9, ub = 9))

SDSD.vs.CC_legoscore.priors <- list(muM = 4.5, muSD = 1.125) 

###lego score
SDSD.vs.CC_legoscore <- BESTmcmc(legoData_final$Correct[legoData_final$SD_beskrivare == 0 & legoData_final$SD_byggare == 0],
                       legoData_final$Correct[legoData_final$SD_beskrivare == 1 & legoData_final$SD_byggare == 1],
                       parallel = T,
                       priors =SDSD.vs.CC_legoscore.priors)
plotAll(SDSD.vs.CC_legoscore)

###lego time
SDSD.vs.CC_legoscore.priors <- list(muM = 300, muSD = 75) #half maximum time

SDSD.vs.CC.legotime <- BESTmcmc(legoData_final$TimeSec[legoData_final$SD_beskrivare == 0 & legoData_final$SD_byggare == 0],
                       legoData_final$TimeSec[legoData_final$SD_beskrivare == 1 & legoData_final$SD_byggare == 1],
                       parallel = T,
                       priors =SDSD.vs.CC_legoscore.priors)
plotAll(SDSD.vs.CC.legotime)

  
#lego efficiency
#no prior since I don't know what to put

SDSD.vs.CC.legoefficiency <- BESTmcmc(legoData_final$efficiency_scaled[legoData_final$SD_beskrivare == 0 & legoData_final$SD_byggare == 0],
                       legoData_final$efficiency_scaled[legoData_final$SD_beskrivare == 1 & legoData_final$SD_byggare == 1],
                       parallel = T)
plotAll(SDSD.vs.CC.legoefficiency)
###########################################
##################TABU#####################
###########################################

tabu.SDSD.vs.CC <- BESTmcmc(Tabu_overall$Correct[Tabu_overall$SD == 0],
                            Tabu_overall$Correct[Tabu_overall$SD == 1],
                            parallel = T)
plotAll(tabu.SDSD.vs.CC)

```

