---
title: "Word guessing (Taboo)"
author: "Benjamin Holding"
output: html_document
---

```{r setup, include=FALSE}
#Setup
knitr::opts_chunk$set(echo = TRUE)

ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
} #function to see if package is installed. Will download if not, and then opens it.

packages <- c("brms", "plyr", "dplyr", "data.table", "lubridate", "tidyr", "xlsx", "tidyr", "apaStyle","sjstats", "BEST", "ggridges", "ggpubr", "tidybayes") #packages that are required
suppressPackageStartupMessages(ipak(packages))

set.seed(782349)

#making seperate folder for tables and plots
mainDir <- getwd()
subDir <- "Tables_and_plots"
ifelse(!dir.exists(file.path(mainDir, subDir)), dir.create(file.path(mainDir, subDir)), FALSE)
```


```{r, include=FALSE}
#Data import and formatting
tabu.initial <- read.csv("Taboo_raw_combined.csv") #reading in long form data

colnames(tabu.initial) <- c("Word",	"Score", "Speaker ID",	"Filename", "Notes") #changing column names

complete.tabu <- tabu.initial[complete.cases(tabu.initial$Score),] #removing missing rows

tabu.data <- fill(complete.tabu, `Speaker ID`) #adding Speaker ID for all rows
tabu.data$Filename <- gsub(".xlsx|TABU_|TAbu_|Tabu_","",tabu.data$Filename) # changing file name to get pair identity
tabu.data <- separate(tabu.data,Filename,into=c("pair","Participant1","Participant2")) #add pair identity and seperate participant roles

tabu.data$Pass[tabu.data$Score==0] <- 1 #calculating number of passess
tabu.data$Pass[tabu.data$Score!=0] <- 0

tabu.data$Correct[tabu.data$Score==1] <- 1 #Calculating number of correct guesses
tabu.data$Correct[tabu.data$Score!=1] <- 0

tabu.data$ForbiddenStop[tabu.data$Score==2] <- 1 # calculating number of forbidden word errors
tabu.data$ForbiddenStop[tabu.data$Score!=2] <- 0

tabu.data$ForbiddenContinue[tabu.data$Score==3] <- 1 #calculating number of forbidden & cont. errors
tabu.data$ForbiddenContinue[tabu.data$Score!=3] <- 0

tabu.data$Error[tabu.data$Score=="x"] <- 1 #calculating number of misc. errors
tabu.data$Error[tabu.data$Score!="x"] <- 0

tabu.data$`Guesser ID`[which(tabu.data$`Speaker ID`==tabu.data$Participant1)] <- tabu.data$Participant2[which(tabu.data$`Speaker ID`==tabu.data$Participant1)] #specifying guesser

tabu.data$`Guesser ID`[which(tabu.data$`Speaker ID`==tabu.data$Participant2)] <- tabu.data$Participant1[which(tabu.data$`Speaker ID`==tabu.data$Participant2)] # specifying guesser

slesi.key <- read.csv("SleSI_Masterkey.csv") #open file containing sleep condition

SpeakerKey <- slesi.key[,c(1,3)] #adding condition information
colnames(SpeakerKey) <- c("Speaker ID","Speaker_SD") #adding condition information
GuesserKey <- slesi.key[,c(1,3)] #adding condition information
colnames(GuesserKey) <- c("Guesser ID","Guesser_SD") #adding condition information
tabu1 <- join(tabu.data,SpeakerKey) #adding condition information
tabu2 <- join(tabu1,GuesserKey) #adding condition information

final.tabu <- dplyr::select(tabu2,
                     c(pair,
                       `Guesser ID`,
                       Guesser_SD,
                       `Speaker ID`,
                       Speaker_SD,
                       Word,
                       Correct,
                       Pass,
                       ForbiddenStop,
                       ForbiddenContinue)
                     ) #create final DF with only required columns

# so I need to rethink this (so that each round is summed - so there should be 6 numbers per pair)

tabu_by_rounds <- final.tabu %>% 
  mutate(round = NA) %>%
  group_by(pair)
  

Round_TF <- NA
for (i in 1:length(final.tabu$`Guesser ID`)) {
  Round_TF[i] <- if_else(identical(final.tabu$`Guesser ID`[i], final.tabu$`Guesser ID`[i-1]), 0, 1)
}

tabu_with_rounds_step1 <- cbind(final.tabu, Tabu_Round = Round_TF)

Tabu_with_rounds <- tabu_with_rounds_step1 %>%
  group_by(pair) %>% 
  mutate(Round = cumsum(Tabu_Round)) %>%
  group_by(pair,Round) %>%
  dplyr::summarise(Correct = sum(Correct), 
            Guesser_ID = mean(as.numeric(`Guesser ID`)), 
            Guesser_SD = mean(as.numeric(Guesser_SD)),
            Speaker_ID = mean(as.numeric(`Speaker ID`)), 
            Speaker_SD = mean(as.numeric(Speaker_SD)),
            total_attempts = sum(Correct,Pass,ForbiddenContinue,ForbiddenContinue))

Tabu_with_rounds <- as.data.frame(Tabu_with_rounds)

Tabu_with_rounds <- Tabu_with_rounds[which(Tabu_with_rounds$pair != 97),] #removing pair with person under 18 years old. 

Tabu_with_rounds$Score_ratio <- Tabu_with_rounds$Correct/Tabu_with_rounds$total_attempts #3rd outcome variable

# calculating N per condition
table(Tabu_with_rounds$Guesser_SD)/3

write.csv(Tabu_with_rounds, "public_data/Taboo_byround_data.csv", row.names= F)
```

#Descriptive statistics
```{r}
Tabu_with_rounds[which(Tabu_with_rounds$Guesser_SD == 0 & Tabu_with_rounds$Speaker_SD == 0),] %>% summarise_all(mean) %>% print.data.frame()
Tabu_with_rounds[which(Tabu_with_rounds$Guesser_SD == 0 & Tabu_with_rounds$Speaker_SD == 0),] %>% summarise_all(sd) %>% print.data.frame()

Tabu_with_rounds[which(Tabu_with_rounds$Guesser_SD != Tabu_with_rounds$Speaker_SD),] %>% summarise_all(mean) %>% print.data.frame()
Tabu_with_rounds[which(Tabu_with_rounds$Guesser_SD != Tabu_with_rounds$Speaker_SD),] %>% summarise_all(sd) %>% print.data.frame()

Tabu_with_rounds[which(Tabu_with_rounds$Guesser_SD  == 1 & Tabu_with_rounds$Speaker_SD == 1),] %>% summarise_all(mean) %>% print.data.frame()
Tabu_with_rounds[which(Tabu_with_rounds$Guesser_SD  == 1 & Tabu_with_rounds$Speaker_SD == 1),] %>% summarise_all(sd) %>% print.data.frame()
```

#Analysis for Round score
```{r,cache=TRUE}

#Setting the priors
priors_tabu = c(set_prior("normal(0,1.5)", class = "b"))

#what is an estimat here: It is the estimated amount by which the log odds of the DV (score) would increase if IV (Sleepdep) were one unit higher.

# Building the model
tabu.intercept.model <- brm(Correct ~ 1  + (1|pair), Tabu_with_rounds, sample_prior = T, cores = 4,family = poisson())

tabu.Speaker.model <- brm(Correct ~ Speaker_SD  + (1|pair), Tabu_with_rounds,prior=priors_tabu, sample_prior = T, cores = 4,family = poisson())

tabu.guesser.model <- brm(Correct ~ Guesser_SD  + (1|pair), Tabu_with_rounds,prior=priors_tabu, sample_prior = T, cores = 4,family = poisson())

tabu.both.model <- brm(Correct~ Speaker_SD+Guesser_SD + (1|pair), Tabu_with_rounds,prior=priors_tabu, sample_prior = T, cores = 4,family = poisson())

tabu.interaction.model <- brm(Correct ~ Speaker_SD*Guesser_SD  + (1|pair), Tabu_with_rounds,prior=priors_tabu, sample_prior = T, cores = 4,family = poisson())

##### model comparison
tabu.model1.waic <- WAIC(tabu.intercept.model) #best model
tabu.model2.waic <- WAIC(tabu.Speaker.model)
tabu.model3.waic <- WAIC(tabu.guesser.model)
tabu.model4.waic <- WAIC(tabu.both.model) 
tabu.model5.waic <- WAIC(tabu.interaction.model)
compare_ic(tabu.model1.waic,tabu.model2.waic,tabu.model3.waic,tabu.model4.waic,tabu.model5.waic) 

tabu.model1.LOO <- LOO(tabu.intercept.model) #best model
tabu.model2.LOO <- LOO(tabu.Speaker.model) 
tabu.model3.LOO <- LOO(tabu.guesser.model)
tabu.model4.LOO <- LOO(tabu.both.model) 
tabu.model5.LOO <- LOO(tabu.interaction.model)
compare_ic(tabu.model1.LOO,tabu.model2.LOO,tabu.model3.LOO,tabu.model4.LOO,tabu.model5.LOO) #same again here

### what about other response distributions?
tabu.gaussian.model <- brm(Correct ~ Speaker_SD+Guesser_SD + (1|pair), Tabu_with_rounds,prior=priors_tabu, sample_prior = T, cores = 4,family = gaussian)

tabu.cumulative.model <- brm(Correct ~ Speaker_SD+Guesser_SD + (1|pair), Tabu_with_rounds,prior=priors_tabu, sample_prior = T, cores = 4,family = cumulative)

tabu.gaussian.model.waic <- WAIC(tabu.gaussian.model) 
tabu.cumulative.model.waic <- WAIC(tabu.cumulative.model) 

compare_ic(tabu.model4.waic,tabu.gaussian.model.waic, tabu.cumulative.model.waic) #cumulative is best

tabu.gaussian.model.LOO <- LOO(tabu.gaussian.model) 
tabu.cumulative.model.LOO <- LOO(tabu.cumulative.model) 
compare_ic(tabu.model4.LOO,tabu.gaussian.model.LOO,tabu.cumulative.model.LOO) #cumulative is best

####best model 
plot(tabu.cumulative.model)
pp_check(tabu.cumulative.model)

tabu.model.summary <- summary(tabu.cumulative.model) #run this to check the parameter estimates
tabu.model.summary

##HDI
Taboo.hdi <-sjstats::hdi(tabu.cumulative.model, prob = 0.95)
hdi.Score_speaker <- Taboo.hdi[7,]; hdi.Score_speaker
hdi.Score_guesser <- Taboo.hdi[8,]; hdi.Score_guesser
```


```{r, include=FALSE}
#Creating tables for the manuscript
simple_taboo <- data.frame(row.names = "Percentage change",
                         Speaker_mu = tabu.model.summary$fixed["Speaker_SD",1],
                         Speaker_HDI_low = hdi.Score_speaker[2],
                         Speaker_HDI_high = hdi.Score_speaker[3],
                         Speaker_sigma = tabu.model.summary$fixed["Speaker_SD",2],
                         Guesser_mu = tabu.model.summary$fixed["Guesser_SD",1],
                         Guesser_HDI_low = hdi.Score_guesser[2],
                         Guesser_HDI_high = hdi.Score_guesser[3],
                         Guesser_sigma = tabu.model.summary$fixed["Guesser_SD",2])

Taboo_table <- round(simple_taboo,2)
Taboo_APA_table <- cbind(Outcome = row.names(Taboo_table), Taboo_table)

myoriginalwd <- getwd()
setwd("Tables_and_plots")
apa.table(data = Taboo_APA_table,
          level1.header = c("",
                            "Speaker", 
                            "Guesser"),
          level1.colspan = c(1,4,4 ),
          level2.header = colnames(Taboo_APA_table),
          number = "1",
          title = "Bayesian Estimation of word guessing game performance",
          filename = "Taboo_table.docx",
          note = "Note. HDI = Highest Density Interval; Std.dev = residual standard deviation",
          save = T)$table
setwd(myoriginalwd)
```

```{r, include=FALSE}
#removing non-randomised participants (2 pairs)
#removing pairs with person with no previous sleep history recorded
Tabu_removed.participants <- Tabu_with_rounds 
Tabu_removed.participants <- Tabu_removed.participants[which(Tabu_removed.participants$pair != 9),] #removing pair with 118
Tabu_removed.participants <- Tabu_removed.participants[which(Tabu_removed.participants$pair != 72),] #removing pair with 673

Tabu_removed.participants.model <- brm(Correct ~ Speaker_SD+Guesser_SD + (1|pair), Tabu_removed.participants,prior=priors_tabu, sample_prior = T, cores = 4,family = cumulative)
########

Tabu_removed.participants_summary <- summary(Tabu_removed.participants.model)
Tabu_removed.participants_hdi <- sjstats::hdi(Tabu_removed.participants.model, prob = 0.95)
Tabu_removed.participants_speaker <- Tabu_removed.participants_hdi[7,]
Tabu_removed.participants_guesser <- Tabu_removed.participants_hdi[8,]

####making S1 table
simple_taboo_subset <- data.frame(row.names = "Round score",
                         Speaker_mu = Tabu_removed.participants_summary$fixed["Speaker_SD",1],
                         Speaker_HDI_low = Tabu_removed.participants_speaker[2],
                         Speaker_HDI_high = Tabu_removed.participants_speaker[3],
                         Speaker_sigma = Tabu_removed.participants_summary$fixed["Speaker_SD",2],
                         Guesser_mu = Tabu_removed.participants_summary$fixed["Guesser_SD",1],
                         Guesser_HDI_low = Tabu_removed.participants_guesser[2],
                         Guesser_HDI_high = Tabu_removed.participants_guesser[3],
                         Guesser_sigma = Tabu_removed.participants_summary$fixed["Guesser_SD",2])

Taboo_table_subset <- round(simple_taboo_subset,2)
Taboo_APA_table_subset <- cbind(Outcome = row.names(Taboo_table_subset), Taboo_table_subset)

myoriginalwd <- getwd()
setwd("Tables_and_plots")
apa.table(data = Taboo_APA_table_subset,
          level1.header = c("",
                            "Speaker", 
                            "Guesser"),
          level1.colspan = c(1,4,4 ),
          level2.header = colnames(Taboo_APA_table_subset),
          number = "1",
          title = "Bayesian Estimation of word guessing game performance",
          filename = "S2 Taboo_table.docx",
          note = "Note. HDI = Highest Density Interval; Std.dev = residual standard deviation",
          save = T)$table
setwd(myoriginalwd)
```

